In [37]:
from numpy.random import seed
seed(1)
import numpy as np
import pandas as pd
import tensorflow
tensorflow.keras.__version__
import matplotlib.pyplot as plt
from matplotlib import style
style.use("ggplot")
from sklearn import tree

In [38]:
# read data
fires_df = pd.read_csv("data/forestfires.csv")
fires_df.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [39]:
X = fires_df.drop(columns=["month", "day"])
y = fires_df["month"].values.reshape(-1,1)
print(X.shape, y.shape)

(517, 11) (517, 1)


In [40]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [41]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)

In [42]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [43]:
#LABEL ENCODER AATEMPT 
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [44]:
list(encoded_y_train)

[6,
 1,
 11,
 1,
 11,
 11,
 1,
 11,
 1,
 11,
 7,
 0,
 7,
 1,
 11,
 11,
 7,
 11,
 1,
 7,
 1,
 1,
 11,
 11,
 7,
 1,
 11,
 7,
 1,
 7,
 1,
 2,
 1,
 11,
 1,
 11,
 7,
 11,
 1,
 5,
 11,
 1,
 11,
 1,
 5,
 1,
 11,
 7,
 1,
 1,
 11,
 1,
 1,
 7,
 1,
 7,
 1,
 7,
 11,
 10,
 1,
 4,
 3,
 1,
 1,
 6,
 11,
 11,
 9,
 11,
 1,
 5,
 7,
 1,
 1,
 11,
 1,
 5,
 3,
 11,
 11,
 11,
 11,
 11,
 11,
 7,
 11,
 1,
 11,
 1,
 11,
 3,
 1,
 11,
 5,
 7,
 1,
 11,
 11,
 11,
 0,
 7,
 2,
 7,
 11,
 7,
 3,
 1,
 1,
 11,
 11,
 11,
 11,
 7,
 11,
 1,
 5,
 10,
 6,
 8,
 6,
 11,
 1,
 1,
 1,
 1,
 7,
 1,
 1,
 5,
 5,
 1,
 11,
 1,
 11,
 5,
 1,
 1,
 1,
 1,
 1,
 11,
 11,
 1,
 7,
 1,
 1,
 1,
 1,
 11,
 1,
 2,
 1,
 1,
 11,
 1,
 11,
 11,
 1,
 11,
 1,
 1,
 1,
 1,
 11,
 11,
 1,
 1,
 1,
 7,
 11,
 5,
 1,
 11,
 1,
 11,
 1,
 7,
 1,
 11,
 11,
 11,
 1,
 1,
 11,
 11,
 1,
 11,
 6,
 1,
 7,
 11,
 6,
 11,
 1,
 11,
 11,
 11,
 1,
 1,
 11,
 7,
 6,
 7,
 11,
 1,
 1,
 11,
 11,
 11,
 11,
 5,
 3,
 1,
 5,
 11,
 10,
 7,
 7,
 2,
 7,
 0,
 11,
 11,
 1,
 0,
 11,
 1,
 11,
 1

In [45]:
# Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [46]:
label_encoder.inverse_transform([0])

array(['apr'], dtype=object)

In [47]:
list(y_train_categorical)

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 

In [48]:
from sklearn.svm import SVC 
model = SVC(kernel='rbf')

In [49]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10],
              'gamma': [0.0001, 0.001, 0.01]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [50]:
grid.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.346, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.346, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.351, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.351, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.351, total=   0.0s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.346, total=   0.0s
[CV] C=1, gamma=0.001 ................................................
[CV] ............

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 5, 10], 'gamma': [0.0001, 0.001, 0.01]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [51]:
grid.best_params_

{'C': 10, 'gamma': 0.01}

In [52]:
X_test_scaled

array([[1.25000000e-01, 0.00000000e+00, 9.47096774e-01, ...,
        2.58823529e-01, 0.00000000e+00, 4.76696857e-04],
       [6.25000000e-01, 4.28571429e-01, 9.22580645e-01, ...,
        5.76470588e-01, 0.00000000e+00, 0.00000000e+00],
       [3.75000000e-01, 5.71428571e-01, 9.67741935e-01, ...,
        2.58823529e-01, 0.00000000e+00, 0.00000000e+00],
       ...,
       [3.75000000e-01, 5.71428571e-01, 8.47741935e-01, ...,
        8.94117647e-01, 0.00000000e+00, 8.23218804e-03],
       [1.25000000e-01, 2.85714286e-01, 9.78064516e-01, ...,
        4.70588235e-01, 0.00000000e+00, 1.78761322e-03],
       [8.75000000e-01, 5.71428571e-01, 9.98709677e-01, ...,
        4.70588235e-01, 8.00000000e-01, 0.00000000e+00]])

In [57]:
predictions = grid.predict(X_test_scaled)
predictions

array(['aug', 'sep', 'sep', 'sep', 'sep', 'aug', 'aug', 'aug', 'aug',
       'aug', 'aug', 'sep', 'mar', 'aug', 'sep', 'sep', 'sep', 'sep',
       'sep', 'aug', 'aug', 'sep', 'sep', 'aug', 'sep', 'sep', 'sep',
       'aug', 'sep', 'aug', 'aug', 'aug', 'aug', 'sep', 'sep', 'sep',
       'sep', 'aug', 'aug', 'aug', 'sep', 'mar', 'aug', 'sep', 'aug',
       'sep', 'aug', 'mar', 'sep', 'sep', 'aug', 'aug', 'sep', 'aug',
       'aug', 'aug', 'sep', 'aug', 'aug', 'sep', 'aug', 'sep', 'sep',
       'mar', 'sep', 'aug', 'aug', 'aug', 'mar', 'aug', 'aug', 'aug',
       'aug', 'mar', 'aug', 'aug', 'aug', 'aug', 'mar', 'aug', 'aug',
       'aug', 'aug', 'mar', 'mar', 'mar', 'sep', 'aug', 'sep', 'sep',
       'aug', 'aug', 'mar', 'sep', 'mar', 'mar', 'aug', 'mar', 'aug',
       'aug', 'sep', 'sep', 'aug', 'sep', 'aug', 'sep', 'sep', 'mar',
       'aug', 'mar', 'mar', 'aug', 'sep', 'sep', 'sep', 'aug', 'aug',
       'aug', 'aug', 'sep', 'sep', 'sep', 'aug', 'aug', 'sep', 'mar',
       'aug', 'mar',

In [61]:
prediction_df = pd.DataFrame ({
    'predicted':predictions,
    'actual_y':y_test,
    'temp':X_test['temp']
})
prediction_df

Exception: Data must be 1-dimensional

In [54]:
grid.score(X_test_scaled, y_test)

0.6846153846153846

In [58]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions)

SyntaxError: unexpected EOF while parsing (<ipython-input-58-beedf5e2f405>, line 2)